name = "lilacs"
author = "alas"
version = "0.4.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "56195aaa52b8dd349b1892b8133800e3f7053334f4dc215947401e8ce9237e11"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.252"

[options]
acceptable-game-versions = []
