name = "lilacs"
author = "alas"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6413153899801bdcc17d70c41c2e2b7d3e66327354da6135532660ca2868f9e5"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.244"

[options]
acceptable-game-versions = []
