name = "lilacs"
author = "alas"
version = "0.2.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3824917a0f66906def26e18a4fd06ba0cae7e555934781e425dab34db8bf5397"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.248"

[options]
acceptable-game-versions = []
